name: 'Run AWS ECS Fargate Task'
description: >-
  Run an AWS ECS Fargate task and execute a custom commands. See the log output of the commands.

branding:
  icon: 'activity'
  color: 'white'

inputs:
  task-definition:
    description: >-
      The name or the ARN of the task definition to use for the task.
    required: true

  subnet-ids:
    description: >-
      The list of subnet IDs for the task to use. If multiple they should be passed as multiline argument
      with one subnet ID per line.
    required: true

  security-group-ids:
    description: >-
      List of security group IDs for the task. If multiple they should be passed as multiline argument
      with one subnet ID per line.
    required: true

  assign-public-ip:
    description: >-
      Assign public a IP to the task.
      Options: `['ENABLED', 'DISABLED']`
    required: false
    default: DISABLED

  cluster:
    description: >-
      Which ECS cluster to start the task in.
    required: false

  override-container:
    description: >-
      Will use `containerOverrides` to run a custom command on the container. If provided, `override-container-command`
      must also be set.
    required: false

  override-container-command:
    description: >-
      The command to run on the container if `override-container` is passed.
    required: false

  override-container-environment:
    description: >-
      Add or override existing environment variables if `override-container` is passed. Provide one per line in key=value format.
    required: false

  tail-logs:
    description: >-
      If set to true, will try to extract the logConfiguration for the first container in the task definition. If
      `override-container` is passed, it will extract the logConfiguration from that container. Tailing logs is only
      possible if the provided container uses the `awslogs` logDriver.
    required: false
    default: 'true'

  task-stopped-wait-for-max-attempts:
    description: >-
      How many times to check if the task is stopped before failing the action. The delay between each check is 6 seconds.
    required: false
    default: 100

  end-pipeline-step-before-task-finish:
    description: >-
      Terminate the pipeline step if the Fargate task has not finished executing.
    required: false
    default: 'false'

outputs:
  task-arn:
    description: 'The full ARN for the task that was ran.'
  task-id:
    description: 'The ID for the task that was ran.'
  log-output:
    description: 'The log output of the task that was ran, if `tail-logs` was set to true.'

runs:
  using: 'node20'
  main: 'dist/index.js'
